"""
Emit a runtime-loadable Lua data module from the refined rows, so any addon can
consume the ability -> buff/debuff map in-game.

    python build_lua.py Warrior warrior_rows_refined.json <out_dir>

Produces <out_dir>/Data/<Class>.lua registering into the AbilityMap namespace.
"""
import json, sys, os, datetime

CLASS_TOKENS = {
    'warrior': 'WARRIOR', 'warlock': 'WARLOCK', 'shaman': 'SHAMAN', 'rogue': 'ROGUE',
    'priest': 'PRIEST', 'paladin': 'PALADIN', 'monk': 'MONK', 'mage': 'MAGE',
    'hunter': 'HUNTER', 'evoker': 'EVOKER', 'druid': 'DRUID',
    'demon hunter': 'DEMONHUNTER', 'death knight': 'DEATHKNIGHT',
    # accept the spaceless forms too ("DeathKnight", "DEMONHUNTER")
    'demonhunter': 'DEMONHUNTER', 'deathknight': 'DEATHKNIGHT',
}

def lua_str(s):
    """Escape a Python string into a Lua double-quoted literal."""
    if s is None:
        return 'nil'
    s = str(s)
    out = []
    for ch in s:
        if ch == '\\':   out.append('\\\\')
        elif ch == '"':  out.append('\\"')
        elif ch == '\n': out.append('\\n')
        elif ch == '\r': out.append('')
        elif ch == '\t': out.append(' ')
        elif ord(ch) < 32: out.append(' ')
        else: out.append(ch)
    return '"' + ''.join(out) + '"'

def lua_num(v):
    if v in (None, '', 'None'):
        return None
    try:
        f = float(v)
        return str(int(f)) if f == int(f) else str(f)
    except (TypeError, ValueError):
        return None

def id_list(s):
    if not s:
        return []
    return [int(x.strip()) for x in str(s).split(',') if x.strip().isdigit()]

def str_list(s):
    if not s:
        return []
    return [x.strip() for x in str(s).split(',') if x.strip()]

def main():
    class_name = sys.argv[1]
    rows = json.load(open(sys.argv[2], encoding='utf-8'))
    out_dir = sys.argv[3]
    key = class_name.lower().strip()
    if key not in CLASS_TOKENS:
        raise SystemExit(f"unknown class '{class_name}' -- expected one of "
                         + ', '.join(sorted(set(CLASS_TOKENS))))
    token = CLASS_TOKENS[key]

    os.makedirs(os.path.join(out_dir, 'Data'), exist_ok=True)
    path = os.path.join(out_dir, 'Data', f'{class_name.replace(" ", "")}.lua')

    L = []
    L.append('-- AUTO-GENERATED by build_lua.py -- do not edit by hand.')
    L.append(f'-- Class: {token}   Rows: {len(rows)}   Generated: {datetime.date.today().isoformat()}')
    L.append('-- Source: live client capture via CCXMap exporter, WoW 12.0.7 (68453).')
    L.append('')
    L.append('local ADDON, ns = ...')
    L.append('ns.data = ns.data or {}')
    L.append('')
    L.append(f'ns.data.{token} = {{')
    L.append(f'  class = "{token}",')
    L.append('  build = "12.0.7 (68453)",')
    L.append('  abilities = {')

    order, groups = [], []
    seen_groups = set()
    for r in rows:
        sid = int(r['SpellID'])
        order.append(sid)
        g = r['Group']
        if g not in seen_groups:
            seen_groups.add(g); groups.append(g)

        # carry spellID inside the entry too, so an entry stays self-describing
        # once a consumer pulls it out of the keyed table.
        f = [f'spellID={sid}', f'name={lua_str(r["Name"])}', f'group={lua_str(r["Group"])}']
        kind = r['Kind'].strip().replace('↳ ', '')
        f.append(f'kind={lua_str(kind)}')
        f.append(f'kind_type={lua_str(r["Type"])}')

        specs = str_list(r['Specs'])
        if specs:
            f.append('specs={' + ','.join(lua_str(s) for s in specs) + '}')
        cd = lua_num(r['Cooldown_s'])
        if cd: f.append(f'cd={cd}')
        ch = lua_num(r['Charges'])
        if ch: f.append(f'charges={ch}')
        b = lua_num(r['BuffID'])
        if b: f.append(f'buff={b}')
        d = lua_num(r['DebuffID'])
        if d: f.append(f'debuff={d}')

        # Kairos lifecycle block: everything needed to configure an AuraContainer
        # for this ability's slot -- which aura, on which unit, how long.
        if b or d:
            au = [f'id={b or d}', f'kind="{"buff" if b else "debuff"}"']
            unit = r.get('AuraUnit')
            if unit: au.append(f'unit="{unit}"')
            dur = lua_num(r.get('AuraDuration'))
            if dur: au.append(f'duration={dur}')
            # Permanent auras (stances) report expirationTime 0 -- countdown logic
            # must not read that as "already expired".
            if r.get('AuraPermanent'): au.append('permanent=true')
            f.append('aura={' + ', '.join(au) + '}')

        ov = lua_num(r.get('Override'))
        if ov: f.append(f'override={ov}')
        if r.get('Affects'):
            f.append('affects={' + ','.join(lua_str(t) for t in r['Affects'].split(',')) + '}')
        alt = id_list(r.get('AltIDs'))
        if alt: f.append('alt={' + ','.join(str(a) for a in alt) + '}')
        tri = r.get('Triage')
        if tri: f.append(f'triage={lua_str(tri)}')
        f.append(f'conf={lua_str(r["Confidence"])}')
        if r.get('Note'): f.append(f'note={lua_str(r["Note"])}')
        if r.get('Desc'): f.append(f'desc={lua_str(r["Desc"])}')

        L.append(f'    [{sid}] = {{ ' + ', '.join(f) + ' },')

    L.append('  },')
    L.append('  order = {' + ','.join(str(s) for s in order) + '},')
    L.append('  groups = {' + ','.join(lua_str(g) for g in groups) + '},')
    L.append('}')
    L.append('')

    open(path, 'w', encoding='utf-8').write('\n'.join(L))
    n_aura = sum(1 for r in rows if r['BuffID'] or r['DebuffID'])
    print(f'wrote {path}')
    print(f'  {len(rows)} abilities, {len(groups)} groups, {n_aura} with verified aura IDs')
    print(f'  {os.path.getsize(path)/1024:.1f} KB')

if __name__ == '__main__':
    main()
